Various fixes
FloEdelmann/fixture-converter pull request #38
Opened 2016-11-03 10:38 UTC by FloEdelmann

See commit descriptions.

@fxedel would you mind looking into this, especially the new 16-bit channel test?

2016-11-16 13:36 UTC, FloEdelmann commented
bump @fxedel

2016-11-16 15:17 UTC, fxedel requested changes
Only some small issues.

2016-11-16 15:17 UTC, fxedel commented on fixtures/martin.json
> +                "dimensions": [425, 245, 240],
as of [fixtures_defaults.js#L19](https://github.com/FloEdelmann/fixture-converter/blob/master/fixtures_defaults.js#L19), dimensions are [width, height, depth]. The manual says "Length: 425 mm, Width: 245 mm, Height: 240 mm". I'd use the manual's length as width and the manual's width as depth (because when you look at the Atomic, 425 mm is definitely its width and not its depth). The height is fine.

So, my proposal: [425, 240, 245]

2016-11-16 15:17 UTC, fxedel commented on fixtures/showtec.json
> +                "dimensions": [330, 245, 460],
Once again, our format is [width, height, depth], the manual's format is WxDxH.
So instead, [330, 460, 245] would be correct.

2016-11-16 15:17 UTC, fxedel commented on fixtures/showtec.json
> +                        {
The manual also includes this capability for frost effect: "0-7 No Function"
This makes sense as it must be possible to disable frost effect.

2016-11-16 15:17 UTC, fxedel commented on fixtures/showtec.json
> +                            "name": "Reset Color wheel after 5 seconds"
Could you write Colorwheel in one word as before?

2016-11-16 15:17 UTC, fxedel commented on fixtures/showtec.json
> +                            "name": "Reset Gobo wheel after 5 seconds"
Could you write Gobowheel in one word as before?

2016-11-16 15:17 UTC, fxedel commented on fixtures/showtec.json
> +                            "name": "Blackout while Pan/Tilt/Gobowheel /Colorwheel"
Could you remove the space after Gobowheel?

2016-11-16 18:16 UTC, FloEdelmann commented
The tests are okay?

2016-11-17 12:40 UTC, fxedel commented
Yes, the tests are fine. But what about the Atomic's dimensions?

2016-11-17 16:03 UTC, fxedel approved these changes

2016-11-17 16:06 UTC, merged